### ISSUE TITLE
Online submission error

### ISSUE THREAD

**Issue by Leavingseason** [recsyschallenge/2017#45]
Hi ,  do you closed the online submission API for the moment?
I am testing the online submit API "https://recsys.xing.com/api/submission"  however , it always response  HTTP Error 500 or 401. 
Offline submit API could work still.

**Comment by dkohlsdorf** [comment]
should be fine i didn't close it and it works for me.

Daniel

**Comment by mvolkovs** [comment]
I also get 500 every time I try to submit. Other endpoints seem to work.

**Comment by dkohlsdorf** [comment]
Weird I can submit did u use the new token generated for you?
You have one for offline and one for online.
Daniel

**Comment by Leavingseason** [comment]
With 90% probability it fails and after re-try many times I can manage to submit the file now. 
One thing still weird is that the accepted number is too low: {"num_accepted_recos":144}

**Comment by dkohlsdorf** [comment]
Not all uploaded items are accepted. there are two options:
a) The users / items are not in your target set
b) you already submitted for these items

Also I tested all machines hosting the API and both respond normally for me.
So I dont know what is happening. In order to debug, try using curl:

+ curl -XPOST -H 'Authorization: Bearer WEl.....TgwNmYtMGJiZGYwOTNkZWY2' 'http://recsys.xing.com/api/online/submission' --data-binary @submission_test.txt

Daniel

**Comment by Leavingseason** [comment]
Could you build a webpage so that we can upload file via a browser ( just like the offline submission )?
I keep failing to submit today with 500 and 401.  Neither API nor curl work for me, and I don't know why.
Every other api works well except this one: /api/online/submission

**Comment by dkohlsdorf** [comment]
Short answer is no, 
I am trying to debug this but browser upload is not what we intended.
I also don’t have the time.

Daniel
